### ISSUE TITLE
bugs: Downloads added with browser extension sometimes not registered + Downloading stuff from Firefox displays random file name

### ISSUE THREAD

**Issue by fiftydinar** [giantpinkrobots/varia#71] opened 2024-03-05 08:33 UTC
With initial Firefox extension support, I see this behavior.

**Comment by giantpinkrobots** [comment] 2024-03-05 13:05
When a download is first added it parses the URL for a file name, but after a second it should update with the actual file name. Can you send a screenshot?

**Comment by fiftydinar** [comment] 2024-03-05 13:18
> When a download is first added it parses the URL for a file name, but after a second it should update with the actual file name. Can you send a screenshot?

Just when I wanted to test this again, so I can send a screenshot, it works correctly.
But on next launch, it doesn't want to download anything. It just says Download Canceled in Firefox.

So I have a mixed experience.

**Comment by giantpinkrobots** [comment] 2024-03-05 13:26
Strange. Did you try to download the same thing from the same link and it didn't register? Or some other file?

**Comment by fiftydinar** [comment] 2024-03-05 13:27
> Strange. Did you try to download the same thing from the same link and it didn't register? Or some other file?

I tried same links 1st, then different ones.

**Comment by giantpinkrobots** [comment] 2024-03-05 13:35
Are you using the Flatpak version?

**Comment by fiftydinar** [comment] 2024-03-05 13:37
> Are you using the Flatpak version?

Yes.
Latest v2024.2.29-2.

Fedora Silverblue 39.

**Comment by giantpinkrobots** [comment] 2024-03-05 13:48
I changed something in the code that may have been causing that. Can you install this flatpak file and test? [https://drive.proton.me/urls/QVBRMZCQ18#Gylufq3sPv62](https://drive.proton.me/urls/QVBRMZCQ18#Gylufq3sPv62)

**Comment by fiftydinar** [comment] 2024-03-05 13:54
> I changed something in the code that may have been causing that. Can you install this flatpak file and test? https://drive.proton.me/urls/QVBRMZCQ18#Gylufq3sPv62

Hmm, I still get some mixed results.

I deleted data before installing this version.

**Comment by fiftydinar** [comment] 2024-03-05 14:25
I catched the duplicate bug.

You just have to download the file from same link a lot of times, while quitting & re-opening the app multiple times too.

![Screenshot from 2024-03-05 15-22-16](https://github.com/giantpinkrobots/varia/assets/65243233/afe8f3dc-8656-4459-921f-050ddf5c78bb)

**Comment by Raul1198** [comment] 2024-04-14 11:41
+1 i too get this download not being sometimes not registered and random file name show in varia but correct file name shown in the file manger 
Random Name - [Screencast from 2024-04-14 17-03-59.webm](https://github.com/giantpinkrobots/varia/assets/29801315/be9e339f-d82f-455a-a8c4-b43cbcf66b79)
using varia version v2024.03.20 on Fedora Worksation 39

**Comment by giantpinkrobots** [comment] 2024-04-24 12:42
I think the thread that is created when a download is added might be acting before aria2 is able to assign the download a file name? I'm honestly not sure, because I can't consistently reproduce this, but to be sure I've moved the function that sets the file name in Varia into the main thread loop. The function now continuously checks if the filename has been changed, and if so, updates it in the GUI.

Now I don't think this is the best way to fix this issue, but I will release it in the next version. Hopefully it will fix the issue then.

Let's keep this issue open for a bit. If you see the same problem after the update, please report it here. If there are no reports for a good while, I will then close the issue.

**Comment by giantpinkrobots** [comment] 2024-05-07 08:27
The fix has been released with v2024.5.7. I will wait a week until I close this issue.

**Closed** 2024-08-27 19:26 UTC
