### ISSUE TITLE
App doesnt work on Flatpak or AUR

### ISSUE THREAD

**Issue by emowmeow** [giantpinkrobots/varia#41] opened 2024-01-26 20:07 UTC
After installing the program from flathub I expierenced this specific issue:
```
$ flatpak run io.github.giantpinkrobots.varia

01/25 21:02:18 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

01/25 21:02:18 [NOTICE] IPv4 RPC: listening on TCP port 6801

01/25 21:02:18 [NOTICE] IPv6 RPC: listening on TCP port 6801
Traceback (most recent call last):
  File "/app/share/varia/../../bin/varia-py.py", line 39, in <module>
    sys.exit(main(VERSION))
             ^^^^^^^^^^^^^
  File "/app/share/varia/varia/variamain.py", line 990, in main
    app.win.exitProgram(app)
    ^^^^^^^
AttributeError: 'MyApp' object has no attribute 'win'
```
also installed from the aur
```
$ varia

01/25 21:05:35 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

01/25 21:05:35 [NOTICE] IPv4 RPC: listening on TCP port 6801

01/25 21:05:35 [NOTICE] IPv6 RPC: listening on TCP port 6801
Traceback (most recent call last):
  File "/usr/share/varia/../../bin/varia-py.py", line 39, in <module>
    sys.exit(main(VERSION))
             ^^^^^^^^^^^^^
  File "/usr/share/varia/varia/variamain.py", line 771, in main
    app.win.exitProgram(app)
    ^^^^^^^
AttributeError: 'MyApp' object has no attribute 'win'

```
I tested this on two different arch machines, I havent any experience with aria2 but this application looks very appealing. Thanks for your work

**Comment by giantpinkrobots** [comment] 2024-01-26 20:17
I actually accidentally pushed a broken build to Flathub. My bad. I submitted a new version today but it takes a little while to update. I think it should arrive in like five to six hours.

**Comment by giantpinkrobots** [comment] 2024-02-11 22:43
I am assuming the problem is solved with the new version. Therefore closing the issue. Please reopen if the issue re-emerges.

**Closed by giantpinkrobots** 2024-02-11 22:43 UTC

**Comment by RashadGasimli** [comment] 2024-05-07 19:04
same here, doesn't work on both of them.
