### ISSUE TITLE
Application horizontal scaling covers X or Pause buttons for each download.

### ISSUE THREAD

**Issue by superuser-miguel** [giantpinkrobots/varia#45] opened 2024-01-30 16:49 UTC
When you scale the application horizontally the X or Pause button disappear, or do not scale with the application. This is not a big issue, but the expected behaviour woould be for the buttons to scale horizontally with the app. See images below.

![2024-01-30_11-42-38](https://github.com/giantpinkrobots/varia/assets/16271056/a4cb79b6-fea8-4639-9228-1a7b9ee26eb1)
![2024-01-30_11-43-01](https://github.com/giantpinkrobots/varia/assets/16271056/85565b84-64c3-4234-a1ed-b56bfe243ab8)

**Comment by giantpinkrobots** [comment] 2024-01-31 09:11
Weird, when I make the window as small as it can be, or as large as my horizontal monitor space, it scales correctly.

[Ekran Kaydı - 2024-01-31 12-08-49.webm](https://github.com/giantpinkrobots/varia/assets/93845996/ccf5b9f0-4704-47cd-8012-0a528eb7f403)

You seem to be using a custom Gtk theme. I don't think it should affect this but can you try it with the stock Adwaita theme as well?

**Comment by giantpinkrobots** [comment] 2024-01-31 14:06
Nevermind, I have reproduced it. It happens when the fine name is too long, and because it displays the full file name, it doesn't scale correctly. I'll look into it.

**Comment by giantpinkrobots** [comment] 2024-01-31 19:29
Fixed with the version v2024.1.31.

**Closed by giantpinkrobots** 2024-01-31 19:29 UTC
